### ISSUE TITLE
Check if completely full screen is possible 

### ISSUE THREAD

**Issue by zstenger93** [zstenger93/Transcendence#136]
if so, do it

**Comment by zstenger93** [comment]
Check Fullscreen API

**Comment by zstenger93** [comment]
webkit prefix for chromium based stuff

**Comment by AzerSD** [comment]
I didn't touch frontend stuff, so everything should work as you left it!!!!!!

**Comment by zstenger93** [comment]
❓ 🤔

**Comment by zstenger93** [comment]
I already did this btw for the game
