### ISSUE TITLE
Fine tune bars in every pong version

### ISSUE THREAD

**Issue by zstenger93** [zstenger93/Transcendence#233]
- We should try to make the bar more responsive than it is
> ~~Normal~~
> ~~AI~~
> ~~3D~~
- Also give the bar some speed increase periodically

> Normal
> AI
> 3D

**Comment by zstenger93** [comment]
Bar is fixed for normal and ai pong, for 3d pong you have to do it, because I'm not Italian enough to read that spaghetti 🍝

**Comment by zstenger93** [comment]
Aight, I was hungry so fixed in 🍝 as well.
Bar speed left to do

**Comment by kvebers** [comment]
Fixed
